apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: docu-talk
  namespace: ai-apps-445910
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/network-interfaces: '[{"network":"vpc-cloudrun","subnetwork":"subnet-cloudrun"}]'
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      serviceAccountName: docu-talk@ai-apps-445910.iam.gserviceaccount.com
      containers:
      - image: europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk:${COMMIT_SHA}
        resources:
          limits:
            memory: "4Gi"
            cpu: "1"