steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk-maintenance:$COMMIT_SHA'
      - '-f'
      - 'deploy/maintenance/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk-maintenance:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - docu-talk
      - '--image'
      - 'europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk-maintenance:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - 'ai-apps-445910'