[theme]
primaryColor = "#0c3b7d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#eaf1fc"
textColor = "#000000"
font = "sans serif"

[server]
maxUploadSize = 32

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "type"